In [1]:
import torch
from Attention import *

In [7]:
a = torch.Tensor([
    [1, 2, 3],
    [6, 9, 8],
    [10, 16, 25],
    [4, 80, 53]
])

In [8]:
a.dim()

2

In [9]:
torch.nn.functional.softmax(a)

C:\Users\LukeLim\AppData\Local\Temp\ipykernel_18624\2430103232.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  torch.nn.functional.softmax(a)


tensor([[9.0031e-02, 2.4473e-01, 6.6524e-01],
        [3.5119e-02, 7.0538e-01, 2.5950e-01],
        [3.0586e-07, 1.2339e-04, 9.9988e-01],
        [9.8542e-34, 1.0000e+00, 1.8795e-12]])

In [10]:
torch.nn.functional.softmax(a).sum(1)

C:\Users\LukeLim\AppData\Local\Temp\ipykernel_18624\3756014145.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  torch.nn.functional.softmax(a).sum(1)


tensor([1.0000, 1.0000, 1.0000, 1.0000])

In [14]:
from torch.nn.functional import softmax

import math

# Scaled Dot-Product Attention
def scaled_dot_product_attention(query, key, value):
    # Q @ KT
    attention = query @ key.T
    print(attention)

    # Scaling
    attention = attention / math.sqrt(key.dim())
    print(attention)

    # SoftMax
    attention = softmax(attention)
    print(attention)

    # @ V
    attention = attention @ value
    return attention

In [15]:
scaled_dot_product_attention(a, a, a)

tensor([[  14.,   48.,  117.,  323.],
        [  48.,  181.,  404., 1168.],
        [ 117.,  404.,  981., 2645.],
        [ 323., 1168., 2645., 9225.]])
tensor([[   9.8995,   33.9411,   82.7315,  228.3955],
        [  33.9411,  127.9863,  285.6711,  825.9008],
        [  82.7315,  285.6711,  693.6718, 1870.2975],
        [ 228.3955,  825.9008, 1870.2975, 6523.0601]])
tensor([[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]])


C:\Users\LukeLim\AppData\Local\Temp\ipykernel_18624\1562431555.py:16: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  attention = softmax(attention)


tensor([[ 4., 80., 53.],
        [ 4., 80., 53.],
        [ 4., 80., 53.],
        [ 4., 80., 53.]])